elanmanweb/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from extender.views import HomeView, hello
from runnow.views import AnswerWizard, FORMS


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^dev/', include('extender.urls', namespace='extend')),
    url(r'^start/$', AnswerWizard.as_view(FORMS)),
    url(r'^api/hello/$', hello, name='hello'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

enhancer/urls.py
from django.conf.urls import url
from .views import *

app_name = 'enhancer'

urlpatterns = [
    url(r'^$', PublicContribListView.as_view(), name='index'),
    url(r'^create/$', PublicContribCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', PublicContribDetailView.as_view(), name='get'),
    url(r'^(?P<slug>[\w-]+)/edit/$', PublicContribUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/del/$', PublicContribDeletelView.as_view(), name='del'),
]

extender/urls.py
""" urls under /dev/ space """

from django.conf.urls import url
from .views import (
    DevView,
    RoleDetailView,
    RoleCreateView,
    RoleUpdateView,
    RoleListView,
    LogicalGroupCreateView,
    LogicalGroupDetailView,
    LogicalGroupUpdateView,
    LogicalGroupListView,
    ConfigSectionCreateView,
    ConfigSectionDetailView,
    ConfigSectionUpdateView,
    ConfigSectionListView,
    RoleTaskCreateView,
    RoleTaskDetailView,
    RoleTaskUpdateView,
    RoleTaskListView,
    ApiCreateView,
    ApiDetailView,
    ApiUpdateView,
    ApiListView,
    ApiSectionCreateView,
    ApiSectionDetailView,
    ApiSectionUpdateView,
    ApiSectionListView,
    ConfigSubDetailView,
    ConfigSubCreateView,
    ConfigSubUpdateView,
    ConfigSubListView,
    ApiSubDetailView,
    ApiSubCreateView,
    ApiSubUpdateView,
    ApiSubListView,
    RoleTemplateDetailView,
    RoleTemplateCreateView,
    RoleTemplateUpdateView,
    RoleTemplateListView,
    ConfigValueDetailView,
    ConfigValueCreateView,
    ConfigValueUpdateView,
    ConfigValueListView,
    ApiValueDetailView,
    ApiValueCreateView,
    ApiValueUpdateView,
    ApiValueListView,
)

app_name = 'extender'

urlpatterns = [
    url(r'^$', DevView.as_view(), name='index'),
    url(r'^role/create/$', RoleCreateView.as_view(), name='createrole'),
    url(r'^role/(?P<slug>[\w-]+)/$', RoleDetailView.as_view(), name='getrole'),
    url(r'^role/(?P<slug>[\w-]+)/edit/$', RoleUpdateView.as_view(), name='editrole'),
    url(r'^role/$', RoleListView.as_view(), name='listrole'),
    url(r'^logicalgroup/create/$', LogicalGroupCreateView.as_view(), name='createlogicalgroup'),
    url(r'^logicalgroup/(?P<slug>[\w-]+)/$', LogicalGroupDetailView.as_view(), name='getlogicalgroup'),
    url(r'^logicalgroup/(?P<slug>[\w-]+)/edit/$', LogicalGroupUpdateView.as_view(), name='editlogicalgroup'),
    url(r'^logicalgroup/$', LogicalGroupListView.as_view(), name='listlogicalgroup'),
    url(r'^configsection/create/$', ConfigSectionCreateView.as_view(), name='createconfigsection'),
    url(r'^configsection/(?P<slug>[\w-]+)/$', ConfigSectionDetailView.as_view(), name='getconfigsection'),
    url(r'^configsection/(?P<slug>[\w-]+)/edit/$', ConfigSectionUpdateView.as_view(), name='editconfigsection'),
    url(r'^configsection/$', ConfigSectionListView.as_view(), name='listconfigsection'),
    url(r'^roletask/create/$', RoleTaskCreateView.as_view(), name='createroletask'),
    url(r'^roletask/(?P<slug>[\w-]+)/$', RoleTaskDetailView.as_view(), name='getroletask'),
    url(r'^roletask/(?P<slug>[\w-]+)/edit/$', RoleTaskUpdateView.as_view(), name='editroletask'),
    url(r'^roletask/$', RoleTaskListView.as_view(), name='listroletask'),
    url(r'^api/create/$', ApiCreateView.as_view(), name='createapi'),
    url(r'^api/(?P<slug>[\w-]+)/$', ApiDetailView.as_view(), name='getapi'),
    url(r'^api/(?P<slug>[\w-]+)/edit/$', ApiUpdateView.as_view(), name='editapi'),
    url(r'^api/$', ApiListView.as_view(), name='listapi'),
    url(r'^apisection/create/$', ApiSectionCreateView.as_view(), name='createapisection'),
    url(r'^apisection/(?P<slug>[\w-]+)/$', ApiSectionDetailView.as_view(), name='getapisection'),
    url(r'^apisection/(?P<slug>[\w-]+)/edit/$', ApiSectionUpdateView.as_view(), name='editapisection'),
    url(r'^apisection/$', ApiSectionListView.as_view(), name='listapisection'),
    url(r'^configsub/create/$', ConfigSubCreateView.as_view(), name='createconfigsub'),
    url(r'^configsub/(?P<slug>[\w-]+)/$', ConfigSubDetailView.as_view(), name='getconfigsub'),
    url(r'^configsub/(?P<slug>[\w-]+)/edit/$', ConfigSubUpdateView.as_view(), name='editconfigsub'),
    url(r'^configsub/$', ConfigSubListView.as_view(), name='listconfigsub'),
    url(r'^apisub/create/$', ApiSubCreateView.as_view(), name='createapisub'),
    url(r'^apisub/(?P<slug>[\w-]+)/$', ApiSubDetailView.as_view(), name='getapisub'),
    url(r'^apisub/(?P<slug>[\w-]+)/edit/$', ApiSubUpdateView.as_view(), name='editapisub'),
    url(r'^apisub/$', ApiSubListView.as_view(), name='listapisub'),
    url(r'^roletemplate/create/$', RoleTemplateCreateView.as_view(), name='createroletemplate'),
    url(r'^roletemplate/(?P<slug>[\w-]+)/$', RoleTemplateDetailView.as_view(), name='getroletemplate'),
    url(r'^roletemplate/(?P<slug>[\w-]+)/edit/$', RoleTemplateUpdateView.as_view(), name='editroletemplate'),
    url(r'^roletemplate/$', RoleTemplateListView.as_view(), name='listroletemplate'),
    url(r'^configvalue/create/$', ConfigValueCreateView.as_view(), name='createconfigvalue'),
    url(r'^configvalue/(?P<slug>[\w-]+)/$', ConfigValueDetailView.as_view(), name='getconfigvalue'),
    url(r'^configvalue/(?P<slug>[\w-]+)/edit/$', ConfigValueUpdateView.as_view(), name='editconfigvalue'),
    url(r'^configvalue/$', ConfigValueListView.as_view(), name='listconfigvalue'),
    url(r'^apivalue/create/$', ApiValueCreateView.as_view(), name='createapivalue'),
    url(r'^apivalue/(?P<slug>[\w-]+)/$', ApiValueDetailView.as_view(), name='getapivalue'),
    url(r'^apivalue/(?P<slug>[\w-]+)/edit/$', ApiValueUpdateView.as_view(), name='editapivalue'),
    url(r'^apivalue/$', ApiValueListView.as_view(), name='listapivalue'),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block head_title %}elanman.org{% endblock head_title %}</title>
    {% include 'snippets/css.html' %}
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col">
            {% include 'snippets/nav.html' %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% include 'snippets/js-pre.html' %}
            {% block content %}{% endblock content %}
            {% include 'snippets/js-post.html' %}
        </div>
    </div>
    <div class="row">
    </div>
</div>
</body>
</html>

templates/dev.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <div class="alert alert-success">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-3">
        <div class="list-group" id="list-tab" role="tablist">
            <a class="list-group-item list-group-item-action active" id="list-roles-list" data-toggle="list"
                href="#list-roles" role="tab" aria-controls="roles">Roles
                <span class="badge badge-secondary float-right">{{ rolelist|length }}</span>
            </a>
            <a class="list-group-item list-group-item-action" id="list-logicalgroup-list" data-toggle="list"
                href="#list-logicalgroup" role="tab" aria-controls="logicalgroup">LogicalGroup
                <span class="badge badge-secondary float-right">{{ logicalgrouplist|length }}</span>
            </a>
            <a class="list-group-item list-group-item-action" id="list-roletasks-list" data-toggle="list"
                href="#list-roletasks" role="tab" aria-controls="roletasks">RoleTasks
                <span class="badge badge-secondary float-right">{{ roletasklist|length }}</span>
            </a>
            <a class="list-group-item list-group-item-action" id="list-roletemplate-list" data-toggle="list"
                href="#list-roletemplates" role="tab" aria-controls="roletemplates">Role Templates
                <span class="badge badge-secondary float-right">{{ roletemplatelist|length }}</span>
            </a>
            <a class="list-group-item list-group-item-action" id="list-configsection-list" data-toggle="list"
                href="#list-configsection" role="tab" aria-controls="configsection">Config Section
                <span class="badge badge-secondary float-right">{{ configsectionlist|length }}</span>
            </a>
            <a class="list-group-item list-group-item-action" id="list-configsub-list" data-toggle="list"
                href="#list-configsubs" role="tab" aria-controls="configsubs">Config Objects
                <span class="badge badge-secondary float-right">{{ configobjectlist|length }}</span>
            </a>
            <a class="list-group-item list-group-item-action" id="list-configvalue-list" data-toggle="list"
                href="#list-configvalues" role="tab" aria-controls="configvalues">Config Values
                <span class="badge badge-secondary float-right">{{ configvaluelist|length }}</span>
            </a>
            <a class="list-group-item list-group-item-action" id="list-api-list" data-toggle="list"
                href="#list-api" role="tab" aria-controls="api">API
                <span class="badge badge-secondary float-right">{{ apilist|length }}</span>
            </a>
            <a class="list-group-item list-group-item-action" id="list-apisection-list" data-toggle="list"
                href="#list-apisections" role="tab" aria-controls="apisections">API Sections
                <span class="badge badge-secondary float-right">{{ apisectionlist|length }}</span>
            </a>
            <a class="list-group-item list-group-item-action" id="list-apisub-list" data-toggle="list"
                href="#list-apisubs" role="tab" aria-controls="apisubs">API Objects
                <span class="badge badge-secondary float-right">{{ apiobjectlist|length }}</span>
            </a>
            <a class="list-group-item list-group-item-action" id="list-apivalue-list" data-toggle="list"
                href="#list-apivalues" role="tab" aria-controls="apivalues">API Values
                <span class="badge badge-secondary float-right">{{ apivaluelist|length }}</span>
            </a>
        </div>
    </div>
    <div class="col-9">
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="list-roles" role="tabpanel" aria-labelledby="list-roles-list">
                Explain Roles...<br>
                <a href='{% url "extend:listrole" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createrole" %}' class="badge badge-success">Create</a>
            </div>
            <div class="tab-pane fade" id="list-logicalgroup" role="tabpanel" aria-labelledby="list-logicalgroup-list">
                Explain Logical Groups...<br>
                <a href='{% url "extend:listlogicalgroup" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createlogicalgroup" %}' class="badge badge-success">Create</a>
            </div>
            <div class="tab-pane fade" id="list-roletasks" role="tabpanel" aria-labelledby="list-roletasks-list">
                Explain Role Tasks...<br>
                <a href='{% url "extend:listroletask" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createroletask" %}' class="badge badge-success">Create</a>
            </div>
            <div class="tab-pane fade" id="list-roletemplates" role="tabpanel" aria-labelledby="list-roletemplate-list">
                Explain Role Templates...<br>
                <a href='{% url "extend:listroletemplate" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createroletemplate" %}' class="badge badge-success">Create</a>
            </div>
            <div class="tab-pane fade" id="list-configsection" role="tabpanel" aria-labelledby="list-configsection-list">
                Explain Config Sections...<br>
                <a href='{% url "extend:listconfigsection" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createconfigsection" %}' class="badge badge-success">Create</a>
            </div>
            <div class="tab-pane fade" id="list-configsubs" role="tabpanel" aria-labelledby="list-configsub-list">
                Explain Config Objects...<br>
                <a href='{% url "extend:listconfigsub" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createconfigsub" %}' class="badge badge-success">Create</a>
            </div>
            <div class="tab-pane fade" id="list-configvalues" role="tabpanel" aria-labelledby="list-configvalue-list">
                Explain Config Values...<br>
                <a href='{% url "extend:listconfigvalue" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createconfigvalue" %}' class="badge badge-success">Create</a>
            </div>
            <div class="tab-pane fade" id="list-api" role="tabpanel" aria-labelledby="list-api-list">
                Explain API...<br>
                <a href='{% url "extend:listapi" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createapi" %}' class="badge badge-success">Create</a>
            </div>
            <div class="tab-pane fade" id="list-apisections" role="tabpanel" aria-labelledby="list-apisection-list">
                Explain API Sections...<br>
                <a href='{% url "extend:listapisection" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createapisection" %}' class="badge badge-success">Create</a>
            </div>
            <div class="tab-pane fade" id="list-apisubs" role="tabpanel" aria-labelledby="list-apisub-list">
                Explain API Objects...<br>
                <a href='{% url "extend:listapisub" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createapisub" %}' class="badge badge-success">Create</a>
            </div>
            <div class="tab-pane fade" id="list-apivalues" role="tabpanel" aria-labelledby="list-apivalue-list">
                Explain API Values...<br>
                <a href='{% url "extend:listapivalue" %}' class="badge badge-primary">List</a>
                <a href='{% url "extend:createapivalue" %}' class="badge badge-success">Create</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/form.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super}}{% endblock head_title %}

{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
{% include 'snippets/form-snippet.html' %}
</div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col">
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="jumbotron">
            <h1 class="display-3">Welcome</h1>
            <p class="lead">The main reason for this site is generate the yaml required for <a
                    href="https://github.com/ilanh/elanman" target="_blank">eLan Manager</a></p>
            <hr class="my-4">
            <p>I'm just starting with the wizard, you can give it a try here:</p>
            <p class="lead">
                <a class="btn btn-primary btn-lg" href="/start/" role="button">Start Wizard</a>
            </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="alert alert-primary">
            <a href="https://github.com/ilanh/" target="_blank">My Projects</a> on github:
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card-group">
            <div class="card">
                <!--<img class="card-img-top" src="holder.js/100px80" alt="Card image cap">-->
                <div class="card-body">
                    <h4 class="card-title">eLanman</h4>
                    <p class="card-text">Ansible playbook to generate another playbook tailor made to your
                        environment.</p>
                    <p class="card-text"><a href="https://github.com/ilanh/elanman" class="btn btn-primary btn-sm"
                                            target="_blank">Go to</a></p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">
                        <div class="input-group input-group-sm">
                            <input type="text" id="cloneem" value="https://github.com/ilanh/elanman.git"
                                   class="form-control">
                            <span class="input-group-btn">
                        <button class="btn btn-secondary" data-clipboard-target="#cloneem" id="copyem">copy</button>
                        </span>
                        </div>
                    </small>
                </div>
            </div>
            <div class="card">
                <!--<img class="card-img-top" src="holder.js/100px80" alt="Card image cap">-->
                <div class="card-body">
                    <h4 class="card-title">MyeLanman</h4>
                    <p class="card-text">The output playbook of elanman if no answer file is given and the sample is
                        applied.</p>
                    <p class="card-text"><a href="https://github.com/ilanh/myelanman" class="btn btn-primary btn-sm"
                                            target="_blank">Go to</a></p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">
                        <div class="input-group input-group-sm">
                            <input type="text" id="clonemyem" value="https://github.com/ilanh/myelanman.git"
                                   class="form-control">
                            <span class="input-group-btn">
                        <button class="btn btn-secondary" data-clipboard-target="#clonemyem" id="copymyem">copy</button>
                        </span>
                        </div>
                    </small>
                </div>
            </div>
            <div class="card">
                <!--<img class="card-img-top" src="holder.js/100px80" alt="Card image cap">-->
                <div class="card-body">
                    <h4 class="card-title">eLanmanWeb</h4>
                    <p class="card-text">This website, eventually will generate answers.yaml to download after running a
                        short wizard</p>
                    <p class="card-text"><a href="https://github.com/ilanh/elanmanweb" class="btn btn-primary btn-sm"
                                            target="_blank">Go to</a></p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">
                        <div class="input-group input-group-sm">
                            <input type="text" id="cloneemweb" value="https://github.com/ilanh/elanmanweb.git"
                                   class="form-control">
                            <span class="input-group-btn">
                        <button class="btn btn-secondary" data-clipboard-target="#cloneemweb"
                                id="copyemweb">copy</button>
                        </span>
                        </div>
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'home/clipboard.min.js' %}"></script>
<script>
    (function(){
    new Clipboard('#copyem');
})();
    (function(){
    new Clipboard('#copymyem');
})();
    (function(){
    new Clipboard('#copyemweb');
})();
</script>
{% endblock content %}