elanmanweb/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from extender.views import HomeView, hello
from runnow.views import AnswerWizard, FORMS


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^dev/', include('extender.urls', namespace='extend')),
    url(r'^start/$', AnswerWizard.as_view(FORMS)),
    url(r'^api/hello/$', hello, name='hello'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

enhancer/urls.py
from django.conf.urls import url
from .views import *

app_name = 'enhancer'

urlpatterns = [
    url(r'^$', PublicContribListView.as_view(), name='index'),
    url(r'^create/$', PublicContribCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', PublicContribDetailView.as_view(), name='get'),
    url(r'^(?P<slug>[\w-]+)/edit/$', PublicContribUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/del/$', PublicContribDeletelView.as_view(), name='del'),
]

enhancer/models.py
from django.db import models
from django.conf import settings
from elanmanweb.utils import unique_slug_generator
from django.urls import reverse
from django.db.models import Q
from django.db.models.signals import pre_save

# Create your models here.
User = settings.AUTH_USER_MODEL


class PublicContribQuerySet(models.QuerySet):
    def search(self, query):
        if query:
            query = query.strip()
            return self.filter(
                Q(exid__icontains=query) |
                Q(exid__iexact=query) |
                Q(shortname__icontains=query) |
                Q(shortname__iexact=query)
            ).distinct()
        return self


class PublicContribManager(models.Manager):
    def get_queryset(self):
        return PublicContribQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class PublicContrib(models.Model):
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    shortname = models.CharField(max_length=32)
    exid = models.CharField(max_length=16, null=True)
    desc = models.CharField(max_length=64, null=True)
    slug = models.SlugField(null=True, blank=True)
    ispublic = models.BooleanField(default=False)
    popularity = models.IntegerField(default=0)

    objects = PublicContribManager()

    def get_absolute_url(self):
        return reverse('enhancer:get', kwargs={'slug': self.slug})

    def get_absolute_url_edit(self):
        return reverse('enhancer:edit', kwargs={'slug': self.slug})

    def __str__(self):
        return self.shortname

    @property
    def title(self):
        return self.exid


def pc_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(pc_pre_save_receiver, sender=PublicContrib)

enhancer/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import PublicContrib


class PublicContribCreateForm(forms.ModelForm):
    class Meta:
        model = PublicContrib
        fields = [
            'shortname',
            'desc',
            'exid',
        ]
        labels = {
            'shortname': _('Short Name'),
            'desc': _('description'),
            'exid': _('External ID'),
        }
        help_texts = {
            'shortname': _('Directory name for that role'),
            'exid': _('Key to link yaml vars'),
        }
        error_messages = {
            'shortname': {
                'max_length': _("Name is too long."),
            },
            'exid': {
                'max_length': _("ID is too long."),
            },
        }

    def __init__(self, owner=None, *args, **kwargs):
        super(PublicContribCreateForm, self).__init__(*args, **kwargs)

enhancer/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from .models import PublicContrib
from .forms import PublicContribCreateForm
from django.urls import reverse_lazy
# Create your views here.


class PublicContribListView(ListView):
    def get_queryset(self):
        if self.request.user is not None:
            combined_queryset = PublicContrib.objects.filter(owner=self.request.user) | \
            PublicContrib.objects.filter(ispublic=True)
        else:
            combined_queryset = PublicContrib.objects.filter(ispublic=True)
        return combined_queryset


class PublicContribDetailView(DetailView):
    def get_queryset(self):
        if self.request.user is not None:
            combined_queryset = PublicContrib.objects.filter(owner=self.request.user) | \
                                PublicContrib.objects.filter(ispublic=True)
        else:
            combined_queryset = PublicContrib.objects.filter(ispublic=True)
        return combined_queryset


class PublicContribDeletelView(DeleteView):
    def get_queryset(self):
        combined_queryset = PublicContrib.objects.filter(owner=self.request.user, ispublic=False)
        return combined_queryset
    success_url = reverse_lazy('enhancer:index')


class PublicContribCreateView(LoginRequiredMixin, CreateView):
    form_class = PublicContribCreateForm
    template_name = 'form.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(PublicContribCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(PublicContribCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Create'
        return context

    def get_form_kwargs(self):
        kwargs = super(PublicContribCreateView, self).get_form_kwargs()
        kwargs['owner'] = self.request.user
        return kwargs


class PublicContribUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PublicContribCreateForm
    template_name = 'form.html'

    def get_context_data(self, *args, **kwargs):
        context = super(PublicContribUpdateView, self).get_context_data(*args, **kwargs)
        shortname = self.get_object().shortname
        context['title'] = f'Update Name: {shortname}'
        return context

    def get_queryset(self):
        return PublicContrib.objects.filter(owner=self.request.user)

    def get_form_kwargs(self):
        kwargs = super(PublicContribUpdateView, self).get_form_kwargs()
        kwargs['owner'] = self.request.user
        return kwargs

enhancer/templates/enhancer/publiccontrib_confirm_delete.html
{% extends "base.html" %}
{% block head_title %}{{ object.title }} | {{ block.super}}{% endblock head_title %}
{% block content %}
{% include 'snippets/detail_top.html' %}
<li class="list-group-item"><b>Short Name:</b> {{ object.shortname }}</li>
<li class="list-group-item"><b>External ID:</b> {{ object.exid }}</li>
<li class="list-group-item"><b>Slug:</b> {{ object.slug }}</li>
<li class="list-group-item"><form action="" method="post">{% csrf_token %}<b>Are you sure you want to delete "{{ object }}"?</b>
    <input type="submit" value="Confirm" class="btn btn-danger float-right"/>
    <a class="btn btn-success float-right" href="{{ object.get_absolute_url }}" role="button">Cencel</a>
</form></li>
{% include 'snippets/detail_bottom.html' %}
{% endblock %}

enhancer/templates/enhancer/publiccontrib_detail.html
{% extends "base.html" %}
{% block head_title %}{{ object.title }} | {{ block.super }}{% endblock head_title %}
{% block content %}
{% include 'snippets/detail_top.html' %}
        <li class="list-group-item"><b>Short Name:</b> {{ object.shortname }}</li>
        <li class="list-group-item"><b>External ID:</b> {{ object.exid }}</li>
        <li class="list-group-item"><b>Slug:</b> {{ object.slug }}</li>
{% if request.user.username == object.owner.username %}<a class="btn btn-danger float-right" href="{{ object.get_absolute_url }}del/" role="button">Delete</a>{% endif %}
{% include 'snippets/detail_bottom.html' %}
{% endblock %}

enhancer/templates/enhancer/publiccontrib_list.html
{% extends "base.html" %}
{% block head_title %}API | {{ block.super}}{% endblock head_title %}
{% block content %}
<div class="table-responsive">
<table class="table table-hover">
    <thead>
    <tr>
        <th>Object list - <a href='{% url "enhancer:create" %}'>Add</a></th>
    </tr>
    </thead>
    <tbody>
    {% for object in object_list %}
    <tr>
        <td><a href="{{ object.get_absolute_url }}" class="navbar-link">{{ object.shortname }}</a></td>
        <td>{{ object.desc }}</td>
        <td>{{ object.slug }}</td>
        <td>{% if request.user.username == object.owner.username %}
            <a href="{{ object.get_absolute_url_edit }}" class="navbar-link">edit</a>{% endif %}
        </td>
    </tr>
    {% empty %}
    <tr>
    <td><a href='{% url "enhancer:create" %}'>Add One</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}